// Static 3CX data ported verbatim from the original UI:
//  - TCX_EXTRA_CATALOGS : curated common fields per entity (with type + default)
//  - TCX_ENDPOINTS      : the addable xAPI entities ("Add endpoint" picker)
//  - GOLDEN_STANDARD_*  : the Default-Fields preset (Phase 5b)

export type FieldType = 'bool' | 'enum' | 'int' | 'list' | 'str'

export interface CatalogField {
  field: string
  type: FieldType
  default: boolean | number | string | string[]
  options?: string[]
}

export interface Endpoint {
  key: string
  label: string
  path: string
  singleton?: boolean
  recommended?: boolean
}

export const TCX_EXTRA_CATALOGS: Record<string, CatalogField[]> = {
  trunks: [
    { field: 'Gateway.DeliverAudio', type: 'bool', default: true },
    { field: 'Gateway.Codecs', type: 'list', default: ['PCMA', 'G722'] },
    { field: 'DisableVideo', type: 'bool', default: false },
    { field: 'Direction', type: 'enum', options: ['Both', 'Inbound', 'Outbound'], default: 'Both' },
    { field: 'EnableInboundCalls', type: 'bool', default: true },
    { field: 'EnableOutboundCalls', type: 'bool', default: true },
    { field: 'DisableCallTransfer', type: 'bool', default: false },
    { field: 'SimultaneousCalls', type: 'int', default: 50 },
    { field: 'DiversionHeader', type: 'bool', default: true },
    { field: 'E164ProcessIncomingNumber', type: 'bool', default: false },
    { field: 'PublishInfo', type: 'bool', default: false },
    { field: 'ReceiveInfo', type: 'bool', default: false },
    { field: 'TunnelEnabled', type: 'bool', default: false },
    { field: 'UseSeparateAuthId', type: 'bool', default: false },
  ],
  users: [
    { field: 'Phones.*.Settings.Codecs', type: 'list', default: ['PCMA', 'G722'] },
    { field: 'Phones.*.Settings.DateFormat', type: 'enum', options: ['15 JAN MON', '15-01-2025', '2025-01-15', '01/15/2025'], default: '15 JAN MON' },
    { field: 'Phones.*.Settings.TimeFormat', type: 'enum', options: ['24-hour clock', '12-hour clock'], default: '24-hour clock' },
    { field: 'Phones.*.Settings.TimeZone', type: 'str', default: '' },
    { field: 'Phones.*.Settings.PhoneLanguage', type: 'str', default: 'English' },
    { field: 'Phones.*.Settings.Backlight', type: 'enum', options: ['Always on', '10 seconds', '30 seconds', '1 minute', '5 minutes', '10 minutes', '30 minutes', '1 hour'], default: '30 seconds' },
    { field: 'Phones.*.Settings.ScreenSaver', type: 'str', default: '' },
    { field: 'Phones.*.Settings.RingTone', type: 'str', default: 'Default' },
    { field: 'Phones.*.Settings.QueueRingTone', type: 'str', default: 'Ring 6' },
    { field: 'Phones.*.Settings.XferType', type: 'enum', options: ['BXfer', 'AXfer'], default: 'BXfer' },
    { field: 'Phones.*.Settings.PowerLed', type: 'str', default: 'Both (Voicemail and Missed calls)' },
    { field: 'Phones.*.Settings.SbcName', type: 'str', default: '' },
    { field: 'Phones.*.TemplateName', type: 'str', default: 'fanvil.ph.xml' },
    { field: 'Language', type: 'str', default: 'en' },
    { field: 'Blfs', type: 'str', default: '<PhoneDevice><BLFS /></PhoneDevice>' },
    { field: 'DeskphonePassword', type: 'str', default: '' },
    { field: 'OutboundCallerID', type: 'str', default: '' },
    { field: 'EmailAddress', type: 'str', default: '' },
    { field: 'Mobile', type: 'str', default: '' },
    { field: 'PbxDeliversAudio', type: 'bool', default: true },
    { field: 'SendEmailMissedCalls', type: 'bool', default: false },
    { field: 'AllowOwnRecordings', type: 'bool', default: true },
    { field: 'RecordCalls', type: 'bool', default: false },
    { field: 'RecordEmailNotify', type: 'bool', default: false },
    { field: 'RecordExternalCallsOnly', type: 'bool', default: false },
    { field: 'VMEnabled', type: 'bool', default: true },
    { field: 'VMPlayCallerID', type: 'bool', default: false },
    { field: 'VMDisablePinAuth', type: 'bool', default: false },
    { field: 'VMEmailOptions', type: 'enum', options: ['AttachmentAndDelete', 'Attachment', 'Notification', 'None'], default: 'Notification' },
    { field: 'VMPlayMsgDateTime', type: 'enum', options: ['None', 'Date', 'Time', 'DateTime'], default: 'None' },
    { field: 'Enable2FA', type: 'bool', default: false },
    { field: 'Require2FA', type: 'bool', default: false },
    { field: 'PinProtected', type: 'bool', default: false },
    { field: 'PinProtectTimeout', type: 'int', default: 60 },
    { field: 'SRTPMode', type: 'str', default: 'SRTPDisabled' },
    { field: 'CallScreening', type: 'bool', default: false },
    { field: 'AllowLanOnly', type: 'bool', default: true },
    { field: 'EnableHotdesking', type: 'bool', default: false },
    { field: 'BlockTunnel', type: 'bool', default: false },
    { field: 'HideInPhonebook', type: 'bool', default: false },
    { field: 'MyPhoneAllowDeleteRecordings', type: 'bool', default: false },
    { field: 'MyPhoneHideForwardings', type: 'bool', default: false },
    { field: 'MyPhonePush', type: 'bool', default: true },
    { field: 'MyPhoneShowRecordings', type: 'bool', default: false },
    { field: 'CallUsEnableChat', type: 'bool', default: true },
    { field: 'CallUsEnablePhone', type: 'bool', default: false },
    { field: 'CallUsEnableVideo', type: 'bool', default: false },
    { field: 'CallUsRequirement', type: 'enum', options: ['Both', 'Chat', 'Phone'], default: 'Both' },
    { field: 'GoogleCalendarEnabled', type: 'bool', default: true },
    { field: 'GoogleContactsEnabled', type: 'bool', default: true },
    { field: 'GoogleSignInEnabled', type: 'bool', default: true },
    { field: 'MS365CalendarEnabled', type: 'bool', default: true },
    { field: 'MS365ContactsEnabled', type: 'bool', default: true },
    { field: 'MS365SignInEnabled', type: 'bool', default: true },
    { field: 'MS365TeamsEnabled', type: 'bool', default: true },
    { field: 'DatevEnabled', type: 'bool', default: false },
    { field: 'AIAgent', type: 'bool', default: false },
    { field: 'TranscriptionMode', type: 'enum', options: ['Inherit', 'Nothing', 'ExternalCallsOnly', 'AllCalls'], default: 'Inherit' },
    { field: 'WebMeetingApproveParticipants', type: 'bool', default: false },
  ],
  outboundrules: [
    { field: 'Prefix', type: 'str', default: '' },
    { field: 'NumberLengthRanges', type: 'str', default: '' },
    { field: 'Priority', type: 'int', default: 0 },
    { field: 'DNRanges', type: 'list', default: [] },
    { field: 'GroupIds', type: 'list', default: [] },
    { field: 'GroupNames', type: 'list', default: [] },
  ],
  holidays: [
    { field: 'IsRecurrent', type: 'bool', default: false },
    { field: 'HolidayPrompt', type: 'str', default: '' },
    { field: 'Day', type: 'int', default: 1 },
    { field: 'DayEnd', type: 'int', default: 1 },
    { field: 'Month', type: 'int', default: 1 },
    { field: 'MonthEnd', type: 'int', default: 1 },
    { field: 'Year', type: 'int', default: 2026 },
    { field: 'YearEnd', type: 'int', default: 2026 },
    { field: 'TimeOfStartDate', type: 'str', default: 'PT0H0M' },
    { field: 'TimeOfEndDate', type: 'str', default: 'PT23H59M' },
  ],
  fxs: [
    { field: 'Language', type: 'str', default: 'English' },
    { field: 'TimeZone', type: 'str', default: '' },
    { field: 'Codecs', type: 'list', default: [] },
    { field: 'Group', type: 'str', default: '' },
    { field: 'Brand', type: 'str', default: '' },
    { field: 'Model', type: 'str', default: '' },
    { field: 'FxsLineCount', type: 'int', default: 10 },
    { field: 'Provisioning.Method', type: 'enum', options: ['SBC', 'Direct', 'STUN', 'RemoteSTUN', 'LOCALLAN', 'REMOTESTUN'], default: 'SBC' },
    { field: 'Provisioning.LocalSipPort', type: 'int', default: 5060 },
    { field: 'Provisioning.LocalAudioPortStart', type: 'int', default: 9000 },
    { field: 'Provisioning.LocalAudioPortEnd', type: 'int', default: 10999 },
    { field: 'Provisioning.LocalInterface', type: 'str', default: '' },
    { field: 'Provisioning.RemoteFQDN', type: 'str', default: '' },
    { field: 'Provisioning.RemotePort', type: 'int', default: 5060 },
    { field: 'Provisioning.SbcName', type: 'str', default: '' },
  ],
  queues: [
    { field: 'PollingStrategy', type: 'enum', options: ['Hunt', 'RingAll', 'PriorityHunt', 'LongestWaiting', 'FewestAnswered', 'Round Robin'], default: 'Hunt' },
    { field: 'RingTimeout', type: 'int', default: 20 },
    { field: 'MasterTimeout', type: 'int', default: 20 },
    { field: 'MaxCallersInQueue', type: 'int', default: 0 },
    { field: 'WrapUpTime', type: 'int', default: 2 },
    { field: 'SLATime', type: 'int', default: 0 },
    { field: 'CallbackEnableTime', type: 'int', default: -1 },
    { field: 'CallbackPrefix', type: 'str', default: '' },
    { field: 'AnnounceQueuePosition', type: 'bool', default: false },
    { field: 'AnnouncementInterval', type: 'int', default: 60 },
    { field: 'PriorityQueue', type: 'bool', default: false },
    { field: 'EnableIntro', type: 'bool', default: false },
    { field: 'PlayFullPrompt', type: 'bool', default: false },
    { field: 'AgentAvailabilityMode', type: 'bool', default: false },
    { field: 'Recording', type: 'enum', options: ['Disabled', 'ForcedRecording', 'NotForcedRecording'], default: 'Disabled' },
    { field: 'TranscriptionMode', type: 'enum', options: ['Inherit', 'Nothing', 'ExternalCallsOnly', 'AllCalls'], default: 'Inherit' },
    { field: 'TypeOfChatOwnershipType', type: 'enum', options: ['AutoAssign', 'RoundRobin', 'Manual'], default: 'AutoAssign' },
    { field: 'VMEmailOptions', type: 'enum', options: ['AttachmentAndDelete', 'Attachment', 'Notification', 'None'], default: 'AttachmentAndDelete' },
    { field: 'CallUsEnableChat', type: 'bool', default: false },
    { field: 'CallUsEnablePhone', type: 'bool', default: false },
    { field: 'CallUsEnableVideo', type: 'bool', default: false },
    { field: 'CallUsRequirement', type: 'enum', options: ['Both', 'Chat', 'Phone'], default: 'Both' },
    { field: 'ResetStatisticsScheduleEnabled', type: 'bool', default: false },
    { field: 'OnHoldFile', type: 'str', default: 'onhold.wav' },
    { field: 'GreetingFile', type: 'str', default: '' },
    { field: 'IntroFile', type: 'str', default: '' },
    { field: 'PromptSet', type: 'str', default: '' },
  ],
  ringgroups: [
    { field: 'RingStrategy', type: 'enum', options: ['RingAll', 'Hunt', 'Paging', 'HuntRandom', 'HuntStartFromOldestCalled'], default: 'RingAll' },
    { field: 'RingTime', type: 'int', default: 30 },
    { field: 'GreetingFile', type: 'str', default: '' },
    { field: 'TranscriptionMode', type: 'enum', options: ['Inherit', 'Nothing', 'ExternalCallsOnly', 'AllCalls'], default: 'Inherit' },
    { field: 'VMEmailOptions', type: 'enum', options: ['AttachmentAndDelete', 'Attachment', 'Notification', 'None'], default: 'AttachmentAndDelete' },
    { field: 'CallUsEnableChat', type: 'bool', default: false },
    { field: 'CallUsEnablePhone', type: 'bool', default: false },
    { field: 'CallUsEnableVideo', type: 'bool', default: false },
    { field: 'CallUsRequirement', type: 'enum', options: ['Both', 'Chat', 'Phone'], default: 'Both' },
    { field: 'ForwardNoAnswer.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External', 'BusyTone'], default: 'VoiceMail' },
    { field: 'ForwardNoAnswer.Type', type: 'str', default: 'Extension' },
    { field: 'BreakRoute.Route.To', type: 'enum', options: ['ProceedWithNoExceptions', 'None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'ProceedWithNoExceptions' },
    { field: 'HolidaysRoute.Route.To', type: 'enum', options: ['ProceedWithNoExceptions', 'None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'ProceedWithNoExceptions' },
    { field: 'OutOfOfficeRoute.Route.To', type: 'enum', options: ['ProceedWithNoExceptions', 'None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'ProceedWithNoExceptions' },
  ],
  inboundrules: [
    { field: 'AlterDestinationDuringHolidays', type: 'bool', default: false },
    { field: 'AlterDestinationDuringOutOfOfficeHours', type: 'bool', default: true },
    { field: 'CallType', type: 'enum', options: ['AllCalls', 'Voice', 'Video', 'Fax', 'Chat'], default: 'AllCalls' },
    { field: 'Condition', type: 'enum', options: ['ForwardAll', 'ForwardDataMatched', 'ForwardCallerIDMatched'], default: 'ForwardAll' },
    { field: 'Data', type: 'str', default: '' },
    { field: 'CustomData', type: 'str', default: '' },
    { field: 'Hours.Type', type: 'enum', options: ['OfficeHours', 'OutsideOfficeHours', 'SpecificHoursExcludingHolidays', 'AnyTime'], default: 'OfficeHours' },
    { field: 'Hours.IgnoreHolidays', type: 'bool', default: false },
    { field: 'OfficeHoursDestination.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External', 'Fax'], default: 'Extension' },
    { field: 'OutOfOfficeHoursDestination.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External', 'Fax'], default: 'Extension' },
    { field: 'HolidaysDestination.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External', 'Fax'], default: 'None' },
  ],
  receptionists: [
    { field: 'Timeout', type: 'int', default: 10 },
    { field: 'TimeoutForwardType', type: 'enum', options: ['EndCall', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External', 'VoiceMail'], default: 'EndCall' },
    { field: 'TimeoutForwardDN', type: 'str', default: '' },
    { field: 'InvalidKeyForwardDN', type: 'str', default: '' },
    { field: 'TransferEnable', type: 'bool', default: true },
    { field: 'UseMSExchange', type: 'bool', default: false },
    { field: 'IVRType', type: 'enum', options: ['Default', 'Standard', 'Direct'], default: 'Default' },
    { field: 'TranscriptionMode', type: 'enum', options: ['Inherit', 'Nothing', 'ExternalCallsOnly', 'AllCalls'], default: 'Inherit' },
    { field: 'PromptFilename', type: 'str', default: '' },
    { field: 'PromptSet', type: 'str', default: '' },
    { field: 'ForwardSmsTo', type: 'str', default: '' },
    { field: 'BreakRoute.Route.To', type: 'enum', options: ['ProceedWithNoExceptions', 'None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'ProceedWithNoExceptions' },
    { field: 'HolidaysRoute.Route.To', type: 'enum', options: ['ProceedWithNoExceptions', 'None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'ProceedWithNoExceptions' },
    { field: 'OutOfOfficeRoute.Route.To', type: 'enum', options: ['ProceedWithNoExceptions', 'None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'ProceedWithNoExceptions' },
  ],
  groups: [
    { field: 'AllowCallService', type: 'bool', default: true },
    { field: 'AnswerAfter', type: 'int', default: 0 },
    { field: 'GloballyVisible', type: 'bool', default: false },
    { field: 'OverrideHolidays', type: 'bool', default: false },
    { field: 'DisableCustomPrompt', type: 'bool', default: true },
    { field: 'TranscriptionMode', type: 'enum', options: ['Inherit', 'Nothing', 'ExternalCallsOnly', 'AllCalls'], default: 'Nothing' },
    { field: 'CallUsEnableChat', type: 'bool', default: false },
    { field: 'CallUsEnablePhone', type: 'bool', default: false },
    { field: 'CallUsEnableVideo', type: 'bool', default: false },
    { field: 'CallUsRequirement', type: 'enum', options: ['Both', 'Chat', 'Phone'], default: 'Both' },
    { field: 'Hours.Type', type: 'enum', options: ['OfficeHours', 'OutsideOfficeHours', 'SpecificHoursExcludingHolidays', 'AnyTime'], default: 'SpecificHoursExcludingHolidays' },
    { field: 'Hours.IgnoreHolidays', type: 'bool', default: false },
    { field: 'BreakTime.Type', type: 'enum', options: ['OfficeHours', 'OutsideOfficeHours', 'SpecificHoursExcludingHolidays', 'AnyTime'], default: 'SpecificHoursExcludingHolidays' },
    { field: 'BreakTime.IgnoreHolidays', type: 'bool', default: false },
    { field: 'OfficeRoute.Route.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'None' },
    { field: 'BreakRoute.Route.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'None' },
    { field: 'HolidaysRoute.Route.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'None' },
    { field: 'OutOfOfficeRoute.Route.To', type: 'enum', options: ['None', 'VoiceMail', 'Extension', 'Queue', 'RingGroup', 'IVR', 'External'], default: 'None' },
  ],
  parameters: [],
  voicemailsettings: [
    { field: 'VMEmailOptions', type: 'enum', options: ['AttachmentAndDelete', 'Attachment', 'Notification', 'None'], default: 'Notification' },
    { field: 'VMPlayCallerID', type: 'bool', default: false },
    { field: 'VMPlayMsgDateTime', type: 'enum', options: ['None', 'Date', 'Time', 'DateTime'], default: 'None' },
    { field: 'VMDisablePinAuth', type: 'bool', default: false },
    { field: 'VMEnabled', type: 'bool', default: true },
  ],
  mailsettings: [
    { field: 'SmtpHost', type: 'str', default: '' },
    { field: 'SmtpPort', type: 'int', default: 587 },
    { field: 'SmtpTls', type: 'bool', default: true },
    { field: 'SmtpUsername', type: 'str', default: '' },
    { field: 'FromAddress', type: 'str', default: '' },
    { field: 'FromDisplayName', type: 'str', default: '' },
    { field: 'NoReplyAddress', type: 'str', default: '' },
  ],
  notificationsettings: [
    { field: 'SendEmailOnVoicemail', type: 'bool', default: true },
    { field: 'SendEmailOnMissedCall', type: 'bool', default: false },
    { field: 'SendEmailOnFax', type: 'bool', default: true },
    { field: 'LowDiskSpacePercent', type: 'int', default: 10 },
    { field: 'MaxEmailCount', type: 'int', default: 0 },
  ],
  antihackingsettings: [
    { field: 'PermanentBlacklistAttempts', type: 'int', default: 100 },
    { field: 'PermanentBlacklistSeconds', type: 'int', default: 3600 },
    { field: 'TemporaryBlacklistAttempts', type: 'int', default: 5 },
    { field: 'TemporaryBlacklistSeconds', type: 'int', default: 150 },
    { field: 'EnableAuthFail', type: 'bool', default: true },
    { field: 'CheckAnonymousCalls', type: 'bool', default: true },
    { field: 'BlockAnonymousCalls', type: 'bool', default: false },
  ],
  countrycodes: [],
  codecssettings: [],
  remotearchivingsettings: [
    { field: 'Enabled', type: 'bool', default: false },
    { field: 'ArchivingType', type: 'enum', options: ['FTP', 'S3', 'Azure', 'SFTP'], default: 'FTP' },
    { field: 'Host', type: 'str', default: '' },
    { field: 'Port', type: 'int', default: 21 },
    { field: 'RemotePath', type: 'str', default: '' },
    { field: 'Username', type: 'str', default: '' },
  ],
  officehours: [],
  generalsettingsforpbx: [
    { field: 'CallHistoryEnabled', type: 'bool', default: true },
    { field: 'HideCallHistoryForUsers', type: 'bool', default: false },
    { field: 'CallRecordingEnabled', type: 'bool', default: false },
  ],
  secureSipsettings: [
    { field: 'TlsEnabled', type: 'bool', default: true },
    { field: 'SrtpEnabled', type: 'bool', default: false },
  ],
  sbcs: [
    { field: 'AudioPort', type: 'int', default: 20000 },
    { field: 'LogLevel', type: 'enum', options: ['Low', 'Medium', 'High', 'Verbose'], default: 'Low' },
    { field: 'LogSize', type: 'int', default: 100 },
    { field: 'Security', type: 'enum', options: ['TLS', 'TCP', 'UDP'], default: 'TLS' },
    { field: 'PassiveServerIsEnabled', type: 'bool', default: false },
    { field: 'PassiveServer', type: 'str', default: '' },
    { field: 'Group', type: 'str', default: '' },
  ],
  fax: [
    { field: 'FaxServer', type: 'bool', default: true },
    { field: 'OutboundCallerId', type: 'str', default: '' },
  ],
}

export const TCX_ENDPOINTS: Endpoint[] = [
  { key: 'trunks', label: 'Trunks', path: '/xapi/v1/Trunks', recommended: true },
  { key: 'users', label: 'Users', path: '/xapi/v1/Users', recommended: true },
  { key: 'outboundrules', label: 'Outbound Rules', path: '/xapi/v1/OutboundRules', recommended: true },
  { key: 'holidays', label: 'Holidays', path: '/xapi/v1/Holidays', recommended: true },
  { key: 'fxs', label: 'Phones (FXS / DECT)', path: '/xapi/v1/Fxs', recommended: true },
  { key: 'inboundrules', label: 'Inbound Rules', path: '/xapi/v1/InboundRules' },
  { key: 'ringgroups', label: 'Ring Groups', path: '/xapi/v1/RingGroups' },
  { key: 'queues', label: 'Queues', path: '/xapi/v1/Queues' },
  { key: 'receptionists', label: 'Receptionists (IVR)', path: '/xapi/v1/Receptionists' },
  { key: 'groups', label: 'Groups / Departments', path: '/xapi/v1/Groups' },
  { key: 'parkings', label: 'Call Parkings', path: '/xapi/v1/Parkings' },
  { key: 'callflowapps', label: 'Call Flow Apps', path: '/xapi/v1/CallFlowApps' },
  { key: 'callflowscripts', label: 'Call Flow Scripts', path: '/xapi/v1/CallFlowScripts' },
  { key: 'sbcs', label: 'SBCs', path: '/xapi/v1/Sbcs' },
  { key: 'sipdevices', label: 'SIP Devices', path: '/xapi/v1/SipDevices' },
  { key: 'didnumbers', label: 'DID Numbers', path: '/xapi/v1/DidNumbers' },
  { key: 'phonetemplates', label: 'Phone Templates', path: '/xapi/v1/PhoneTemplates' },
  { key: 'fxstemplates', label: 'FXS Templates', path: '/xapi/v1/FxsTemplates' },
  { key: 'trunktemplates', label: 'Trunk Templates', path: '/xapi/v1/TrunkTemplates' },
  { key: 'firmwares', label: 'Phone Firmwares', path: '/xapi/v1/Firmwares' },
  { key: 'phonelogos', label: 'Phone Logos', path: '/xapi/v1/PhoneLogos' },
  { key: 'fax', label: 'Fax', path: '/xapi/v1/Fax' },
  { key: 'customprompts', label: 'Custom Prompts', path: '/xapi/v1/CustomPrompts' },
  { key: 'promptsets', label: 'Prompt Sets', path: '/xapi/v1/PromptSets' },
  { key: 'emailtemplate', label: 'Email Templates', path: '/xapi/v1/EmailTemplate' },
  { key: 'playlists', label: 'Music-On-Hold Playlists', path: '/xapi/v1/Playlists' },
  { key: 'parameters', label: 'Parameters (system-wide)', path: '/xapi/v1/Parameters', recommended: true },
  { key: 'tenantproperties', label: 'Tenant Properties', path: '/xapi/v1/TenantProperties' },
  { key: 'networkinterfaces', label: 'Network Interfaces', path: '/xapi/v1/NetworkInterfaces' },
  { key: 'callcostsettings', label: 'Call Cost Settings', path: '/xapi/v1/CallCostSettings' },
  { key: 'countries', label: 'Countries (reference)', path: '/xapi/v1/Countries' },
  { key: 'services', label: 'Services (status)', path: '/xapi/v1/Services' },
  { key: 'voicemailsettings', label: 'Voicemail Settings', path: '/xapi/v1/VoicemailSettings', singleton: true, recommended: true },
  { key: 'mailsettings', label: 'Email / SMTP Server', path: '/xapi/v1/MailSettings', singleton: true, recommended: true },
  { key: 'notificationsettings', label: 'Notifications & Alerts', path: '/xapi/v1/NotificationSettings', singleton: true, recommended: true },
  { key: 'antihackingsettings', label: 'Anti-Hacking Settings', path: '/xapi/v1/AntiHackingSettings', singleton: true, recommended: true },
  { key: 'countrycodes', label: 'Country Codes (allowed)', path: '/xapi/v1/CountryCodes', singleton: true, recommended: true },
  { key: 'codecssettings', label: 'Codecs Settings', path: '/xapi/v1/CodecsSettings', singleton: true, recommended: true },
  { key: 'remotearchivingsettings', label: 'Remote Archiving / Backup', path: '/xapi/v1/RemoteArchivingSettings', singleton: true, recommended: true },
  { key: 'officehours', label: 'Office Hours', path: '/xapi/v1/OfficeHours', singleton: true, recommended: true },
  { key: 'generalsettingsforpbx', label: 'General PBX Settings', path: '/xapi/v1/GeneralSettingsForPbx', singleton: true },
  { key: 'secureSipsettings', label: 'Secure SIP / SRTP', path: '/xapi/v1/SecureSipSettings', singleton: true },
  { key: 'cdrsettings', label: 'CDR Settings', path: '/xapi/v1/CDRSettings', singleton: true },
  { key: 'musicon-holdsettings', label: 'Music On Hold Settings', path: '/xapi/v1/MusicOnHoldSettings', singleton: true },
  { key: 'conferencesettings', label: 'Conference Settings', path: '/xapi/v1/ConferenceSettings', singleton: true },
  { key: 'phonessettings', label: 'Phones Settings', path: '/xapi/v1/PhonesSettings', singleton: true },
  { key: 'faxserversettings', label: 'Fax Server Settings', path: '/xapi/v1/FaxServerSettings', singleton: true },
  { key: 'blocklist', label: 'IP Blocklist / Whitelist', path: '/xapi/v1/Blocklist', recommended: true },
  { key: 'blacklistnumbers', label: 'Blacklist Numbers', path: '/xapi/v1/BlackListNumbers', recommended: true },
  { key: 'mytokens', label: 'My API Tokens', path: '/xapi/v1/MyTokens' },
  { key: 'securitytokens', label: 'Security Tokens', path: '/xapi/v1/SecurityTokens' },
  { key: 'peers', label: 'Peers (extensions list)', path: '/xapi/v1/Peers' },
  { key: 'contacts', label: 'Contacts', path: '/xapi/v1/Contacts' },
  { key: 'websitelinks', label: 'Website Links', path: '/xapi/v1/WebsiteLinks' },
  { key: 'emergencygeolocations', label: 'Emergency Geo Locations', path: '/xapi/v1/EmergencyGeoLocations' },
  { key: 'recordings', label: 'Recordings', path: '/xapi/v1/Recordings' },
  { key: 'backups', label: 'Backups (list)', path: '/xapi/v1/Backups' },
  { key: 'eventlogs', label: 'Event Logs', path: '/xapi/v1/EventLogs' },
  { key: 'serviceprincipals', label: 'Service Principals', path: '/xapi/v1/ServicePrincipals' },
]

export const GOLDEN_STANDARD_PRESET = ['outboundrules', 'notificationsettings', 'parameters']
export const GOLDEN_PARAMETERS_FILTER = 'NOTALLOWED_COUNTRYCODES, MS_LOCAL_CODEC_LIST, MS_EXTERNAL_CODEC_LIST'

export function endpointByKey(key: string): Endpoint | undefined {
  return TCX_ENDPOINTS.find((e) => e.key === key)
}

export function catalogFor(key: string): CatalogField[] {
  return TCX_EXTRA_CATALOGS[key] ?? []
}
